### ISSUE TITLE
Code Review for Jerome

### ISSUE THREAD

**Issue by hughjazzman** [AY2223S2-CS2113-T11-4/tp#139]
# @jeromeongithub

- [x] Consider adding JavaDoc for [all non-trivial methods in `Task`](https://github.com/AY2223S2-CS2113-T11-4/tp/blob/master/src/main/java/seedu/todolist/task/Task.java).
- [x] Consider being consistent and [avoid this use of `this` when not necessary, following the coding standards](https://se-education.org/guides/conventions/java/index.html#variables).
https://github.com/AY2223S2-CS2113-T11-4/tp/blob/58d97c30594a0a1f1afe68b1661a562ca5199133/src/main/java/seedu/todolist/task/Task.java#L99-L125
- [x] Might there be magic numbers here?
https://github.com/AY2223S2-CS2113-T11-4/tp/blob/58d97c30594a0a1f1afe68b1661a562ca5199133/src/main/java/seedu/todolist/task/Task.java#L66
- [x] Consider adding JavaDoc to this method
https://github.com/AY2223S2-CS2113-T11-4/tp/blob/58d97c30594a0a1f1afe68b1661a562ca5199133/src/main/java/seedu/todolist/storage/Storage.java#L91
- [x] (Joint with @clement559, in #142) Consider breaking up this constructor and add some JavaDoc - seems slightly complicated.
https://github.com/AY2223S2-CS2113-T11-4/tp/blob/58d97c30594a0a1f1afe68b1661a562ca5199133/src/main/java/seedu/todolist/ToDoListManager.java#L29

**Comment by jeromeongithub** [comment]
Note that some of the author tags changed and the respective authors dealt with those issues.
