### ISSUE TITLE
[PE-D][Tester C] Delete tag command crashes the programme (with tags added)

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T11-4/tp#95]
![Screenshot 2023-03-31 at 17.23.24.png](https://raw.githubusercontent.com/Ju-Can/ped/main/files/8ef915bc-bf6a-4cbd-9043-4614e00510b7.png)

Delete all tags command crashes the programme despite multiple tags added

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Ju-Can/ped#6

**Comment by ERJUNZE** [comment]
Duplicate of #89
